# Generated by Django 6.1 on 2026-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("nutrition", "0008_dietarytag_macrofilter_fooditem_dietary_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="meal_preferences",
            field=models.ManyToManyField(
                blank=True, related_name="users_preferring", to="nutrition.dietarytag"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="meal_preferences_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="starting_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="starting_weight_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("lb", "lb")], default="kg", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="workout_preferences",
            field=models.TextField(blank=True),
        ),
    ]
