# Generated by Django 6.1 on 2026-09-10 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_age_user_height_cm_user_meal_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="workout_preferences",
        ),
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gym_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home gym"),
                    ("commercial", "Commercial gym"),
                    ("outdoor", "Outdoor / park"),
                    ("none", "No gym (bodyweight only)"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="workout_days_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="workout_session_minutes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
