# Generated by Django 6.1 on 2026-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_workout_preferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="injury_notes",
            field=models.TextField(blank=True),
        ),
    ]
