# Split by hand from the autogenerated single migration so the data backfill
# (0006) can run while `role` still exists, before it's removed (0007).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_injury_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_trainee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_trainer",
            field=models.BooleanField(default=False),
        ),
    ]
