# Generated by Django 6.1 on 2026-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_role_alter_user_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unspecified", "Prefer not to say"),
                ],
                default="unspecified",
                max_length=11,
            ),
        ),
    ]
