# Generated by Django 6.1 on 2026-08-26 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("seeded", "Seeded"), ("off", "Open Food Facts")],
                        default="seeded",
                        max_length=10,
                    ),
                ),
                (
                    "calories_per_100g",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "protein_g_per_100g",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "carbs_g_per_100g",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("fat_g_per_100g", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "fiber_g_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "sugar_g_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "sodium_mg_per_100g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainee",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="nutrition.dietplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceMealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_weight_grams",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_meal_items",
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutrition.referencemeal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_weight_grams",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trainee",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reference_meal_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="nutrition.referencemealitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
    ]
