# Generated by Django 6.1 on 2026-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_foodlog_calories_foodlog_carbs_g_foodlog_fat_g_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="calcium_mg_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="iron_mg_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="potassium_mg_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="vitamin_a_mcg_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="vitamin_c_mg_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlog",
            name="calcium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlog",
            name="iron_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlog",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlog",
            name="vitamin_a_mcg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlog",
            name="vitamin_c_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
