# Generated by Django 6.1 on 2026-08-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_fooditem_approval_status_fooditem_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="serving_size_grams",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="serving_unit",
            field=models.CharField(
                choices=[
                    ("g", "Grams"),
                    ("cup", "Cups"),
                    ("oz", "Ounces"),
                    ("lb", "Pounds"),
                    ("each", "Each"),
                    ("serving", "Serving"),
                ],
                default="g",
                max_length=10,
            ),
        ),
    ]
