# Generated by Django 6.1 on 2026-08-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_fooditem_serving_size_grams_fooditem_serving_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencemealitem",
            name="meal",
        ),
        migrations.CreateModel(
            name="MealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="nutrition.referencemeal",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="referencemealitem",
            name="option",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nutrition.mealoption",
            ),
            preserve_default=False,
        ),
    ]
