# Generated by Django 6.1 on 2026-08-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0006_remove_referencemealitem_meal_mealoption_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggedMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("plan", "From plan"),
                            ("custom", "Custom (off plan)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logged_meals",
                        to="nutrition.referencemeal",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["reference_meal__order"],
                "unique_together": {("trainee", "reference_meal", "date")},
            },
        ),
        migrations.AddField(
            model_name="foodlog",
            name="logged_meal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nutrition.loggedmeal",
            ),
        ),
    ]
