# Generated by Django 6.1 on 2026-08-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0007_loggedmeal_foodlog_logged_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MacroFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="fooditem",
            name="dietary_tags",
            field=models.ManyToManyField(
                blank=True, related_name="food_items", to="nutrition.dietarytag"
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="macro_filters",
            field=models.ManyToManyField(
                blank=True, related_name="food_items", to="nutrition.macrofilter"
            ),
        ),
    ]
