# Generated by Django 6.1 on 2026-09-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0008_dietarytag_macrofilter_fooditem_dietary_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietplan",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diet_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loggedmeal",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logged_meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quicklogitem",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quick_log_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
