# Generated by Django 6.1 on 2026-09-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0009_alter_dietplan_trainee_alter_foodlog_trainee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("trainees", "My Trainees"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
