# Generated by Django 6.1 on 2026-09-16 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0011_fooditemeditrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="serving_size_grams",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="serving_unit",
        ),
        migrations.CreateModel(
            name="FoodItemMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("grams_per_unit", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="nutrition.fooditem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("food_item", "label"),
                        name="unique_measure_label_per_food_item",
                    )
                ],
            },
        ),
    ]
