# Generated by Django 6.1 on 2026-09-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0012_remove_fooditem_serving_size_grams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedmeal",
            name="source",
            field=models.CharField(
                choices=[
                    ("plan", "From plan"),
                    ("custom", "Custom (off plan)"),
                    ("mixed", "Mixed (plan + off plan)"),
                ],
                max_length=10,
            ),
        ),
    ]
