# Generated by Django 6.1 on 2026-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0013_alter_loggedmeal_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarytag",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
