# Generated by Django 6.1 on 2026-09-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0014_dietarytag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="fdc_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("seeded", "Seeded"),
                    ("off", "Open Food Facts"),
                    ("usda", "USDA FoodData Central"),
                ],
                default="seeded",
                max_length=10,
            ),
        ),
    ]
