# Generated by Django 6.1 on 2026-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0015_fooditem_fdc_id_alter_fooditem_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="brand_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="fooditemmeasure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("food_item",),
                name="one_default_measure_per_food_item",
            ),
        ),
    ]
