# Generated by Django 6.1 on 2026-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0017_fooditem_trigram_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlog",
            name="custom_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("plan", "Planned meal item"),
                    ("food_item", "Food bank item (barcode/manual)"),
                    ("quick", "Quick-log item"),
                    ("custom", "One-time custom entry"),
                ],
                default="plan",
                max_length=10,
            ),
        ),
    ]
