# Generated by Django 6.1 on 2026-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0018_foodlog_custom_name_alter_foodlog_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="quicklogitem",
            name="calcium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="quicklogitem",
            name="iron_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="quicklogitem",
            name="potassium_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="quicklogitem",
            name="vitamin_a_mcg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="quicklogitem",
            name="vitamin_c_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
