# Generated by Django 6.1 on 2026-09-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0019_quicklogitem_calcium_mg_quicklogitem_iron_mg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlog",
            name="planned_food_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="loggedmeal",
            name="meal_option_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loggedmeal",
            name="reference_meal_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="foodlog",
            name="reference_meal_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="nutrition.referencemealitem",
            ),
        ),
        migrations.AlterField(
            model_name="loggedmeal",
            name="reference_meal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_meals",
                to="nutrition.referencemeal",
            ),
        ),
    ]
