# Generated by Django 6.1 on 2026-09-29 03:15

from django.db import migrations


def backfill(apps, schema_editor):
    """Fill the new snapshot fields for logs saved before they existed, while
    every plan link is still live."""
    LoggedMeal = apps.get_model("nutrition", "LoggedMeal")
    FoodLog = apps.get_model("nutrition", "FoodLog")

    for log in FoodLog.objects.filter(reference_meal_item__isnull=False).select_related(
        "reference_meal_item__food_item"
    ):
        log.planned_food_name = log.reference_meal_item.food_item.name
        log.save(update_fields=["planned_food_name"])

    for meal in LoggedMeal.objects.filter(reference_meal__isnull=False).select_related("reference_meal"):
        meal.reference_meal_label = meal.reference_meal.label
        if meal.source == "plan":
            first_item = (
                meal.items.filter(reference_meal_item__isnull=False)
                .select_related("reference_meal_item__option")
                .first()
            )
            meal.meal_option_label = first_item.reference_meal_item.option.label if first_item else None
        meal.save(update_fields=["reference_meal_label", "meal_option_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0020_orphan_safe_diet_logs"),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
