# Generated by Django 6.1 on 2026-09-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0021_backfill_diet_log_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
