# Generated by Django 6.1 on 2026-09-29 03:33

from datetime import timedelta

from django.db import migrations
from django.db.models import Count, Min


def publish_existing(apps, schema_editor):
    """Every pre-versioning plan was live. Per trainee, the plan the app was
    actually showing (most logged against, then most content, then oldest)
    becomes the active version, effective from before its first log so every
    past log still resolves to it. Any other plan becomes an older, superseded
    version - or is removed if it's an empty, never-logged stray."""
    DietPlan = apps.get_model("nutrition", "DietPlan")
    LoggedMeal = apps.get_model("nutrition", "LoggedMeal")

    plans = DietPlan.objects.annotate(
        log_count=Count("meals__logged_meals", distinct=True),
        meal_count=Count("meals", distinct=True),
    ).order_by("trainee_id", "-log_count", "-meal_count", "id")

    by_trainee = {}
    for plan in plans:
        by_trainee.setdefault(plan.trainee_id, []).append(plan)

    for trainee_plans in by_trainee.values():
        primary, *others = trainee_plans

        def start_date(plan):
            first_log = LoggedMeal.objects.filter(reference_meal__diet_plan=plan).aggregate(d=Min("date"))["d"]
            created = plan.created_at.date()
            return min(created, first_log) if first_log else created

        primary.effective_from = start_date(primary)
        primary.published_at = primary.created_at
        primary.save(update_fields=["effective_from", "published_at"])

        for plan in others:
            if plan.log_count == 0 and plan.meal_count == 0:
                plan.delete()
                continue
            plan.effective_from = min(start_date(plan), primary.effective_from - timedelta(days=1))
            plan.published_at = plan.created_at
            plan.save(update_fields=["effective_from", "published_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0022_plan_versions"),
    ]

    operations = [migrations.RunPython(publish_existing, migrations.RunPython.noop)]
