# Generated by Django 6.1 on 2026-10-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0023_publish_existing_diet_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedmeal",
            name="eaten_at",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
