# Generated by Django 6.1 on 2026-10-01 04:48

from django.db import migrations

# Snapshot of the starting diet vocabulary (also in seed_food_filters_and_tags)
# so every environment has options in onboarding's meal-preferences dropdown
# without anyone remembering to run the seed command - an empty table left
# trainees with nothing but a blank search box. get_or_create: never touches
# a tag that already exists, including user-added ones.
DIETARY_TAGS = {
    "Vegan": "No animal products at all - meat, dairy, eggs, or honey.",
    "Vegetarian": "No meat or fish, but dairy and eggs are fine.",
    "Pescatarian": "Vegetarian, plus fish and seafood.",
    "Gluten-Free": "No wheat, barley, rye, or other gluten-containing grains.",
    "Dairy-Free": "No milk, cheese, yogurt, or other dairy.",
    "Keto": "Very low-carb, high-fat - typically under ~50g of carbs a day.",
    "Low-Carb": "Reduced carbs, less strict than keto.",
    "Low-Fat": "Limits fats and oils - leaner meats, less butter and fried food.",
    "High-Protein": "Prioritizes protein-dense foods.",
    "Paleo": "Whole foods only - no grains, dairy, or processed sugar.",
    "Mediterranean": "Plenty of vegetables, fish, olive oil, and whole grains; little red meat.",
    "Nut-Free": "No tree nuts or peanuts.",
    "Soy-Free": "No soy or soy-derived ingredients.",
    "Carnivore": "Animal products only - meat, fish, and eggs, no plant foods.",
    "Halal": "Follows Islamic dietary law - no pork or alcohol, halal-slaughtered meat.",
    "Kosher": "Follows Jewish dietary law - no pork or shellfish, meat and dairy kept apart.",
}


def seed_dietary_tags(apps, schema_editor):
    DietaryTag = apps.get_model("nutrition", "DietaryTag")
    for name, description in DIETARY_TAGS.items():
        tag, created = DietaryTag.objects.get_or_create(name=name, defaults={"description": description})
        if not created and not tag.description:
            tag.description = description
            tag.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0024_loggedmeal_eaten_at"),
    ]

    operations = [migrations.RunPython(seed_dietary_tags, migrations.RunPython.noop)]
