# Generated by Django 6.1 on 2026-09-10 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="calories_burned",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="readiness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="sleep_quality",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dailymetric",
            name="water_intake_ml",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
