# Generated by Django 6.1 on 2026-09-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_activitylog_calories_burned_activitylog_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailymetric",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
