# Generated by Django 6.1 on 2026-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_activitylog_activity_met_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetric",
            name="bedtime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
