# Generated by Django 6.1 on 2026-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_dailymetric_bedtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetric",
            name="active_energy_kcal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
