# Generated by Django 6.1 on 2026-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_dailymetric_active_energy_kcal"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitymet",
            name="steps_per_minute",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
