# Generated by Django 6.1 on 2026-09-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_selected",
                    models.CharField(
                        choices=[
                            ("no_preference", "No preference"),
                            ("specific_trainer", "Specific trainer"),
                            ("train_myself", "Train myself"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_trainer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_manual_assignment", "Pending manual assignment"),
                            ("active", "Active"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="pending_manual_assignment",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_trainer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "trainer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_trainer_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee",
                    models.OneToOneField(
                        limit_choices_to={"role": "trainee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
