# Generated by Django 6.1 on 2026-09-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0003_planchangelog_trainerprivatenote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="planchangelog",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_change_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qathread",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qa_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainerconnection",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_trainer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_trainer_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainerconnection",
            name="trainee",
            field=models.OneToOneField(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_connection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainernote",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainerprivatenote",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainerprivatenote",
            name="trainer",
            field=models.ForeignKey(
                limit_choices_to={"is_trainer": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
