# Generated by Django 6.1 on 2026-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "connection",
            "0004_alter_planchangelog_trainee_alter_qathread_trainee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qathread",
            name="trainee_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainernote",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
