# Generated by Django 6.1 on 2026-08-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="planexercise",
            name="name",
        ),
        migrations.AddField(
            model_name="loggedset",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("lb", "lb")], default="kg", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="planday",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=15,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="exercises/"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "alternatives",
                    models.ManyToManyField(blank=True, to="workouts.exercise"),
                ),
                (
                    "muscle_groups",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="workouts.musclegroup"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="planexercise",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_exercises",
                to="workouts.exercise",
            ),
            preserve_default=False,
        ),
    ]
