# Generated by Django 6.1 on 2026-08-29 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_musclegroup_remove_planexercise_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutsession",
            name="plan_day",
        ),
        migrations.RemoveField(
            model_name="planexercise",
            name="day",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="muscle_groups",
        ),
        migrations.RemoveField(
            model_name="planexercise",
            name="target_reps",
        ),
        migrations.AddField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exercise",
            name="primary_muscle_groups",
            field=models.ManyToManyField(
                blank=True, related_name="primary_exercises", to="workouts.musclegroup"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscle_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_exercises",
                to="workouts.musclegroup",
            ),
        ),
        migrations.AddField(
            model_name="loggedset",
            name="is_warmup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loggedset",
            name="rpe",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="planexercise",
            name="target_reps_max",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="planexercise",
            name="target_reps_min",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="sessions_per_week",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="PlanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="planexercise",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workouts.plansession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="plan_session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logged_sessions",
                to="workouts.plansession",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PlanDay",
        ),
    ]
