# Generated by Django 6.1 on 2026-08-29 01:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_remove_workoutsession_plan_day_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutsession",
            unique_together={("trainee", "plan_session", "date")},
        ),
    ]
