# Generated by Django 6.1 on 2026-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_alter_workoutsession_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="planexercise",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plansession",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
