# Generated by Django 6.1 on 2026-09-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_planexercise_notes_plansession_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"is_trainee": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
