# Generated by Django 6.1 on 2026-09-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0008_planexercise_superset_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedexercise",
            name="substituted_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workouts.exercise",
            ),
        ),
        migrations.AddField(
            model_name="loggedexercise",
            name="superset_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workouts.planexercise",
            ),
        ),
    ]
