# Generated by Django 6.1 on 2026-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0010_exercise_is_unilateral_loggedset_reps_done_left_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedset",
            name="is_dropset",
            field=models.BooleanField(default=False),
        ),
    ]
