# Generated by Django 6.1 on 2026-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0011_loggedset_is_dropset"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="calories_burned",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
