# Generated by Django 6.1 on 2026-09-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0012_workoutsession_calories_burned"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedexercise",
            name="planned_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="workouts.exercise",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="plan_session_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="loggedexercise",
            name="plan_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_instances",
                to="workouts.planexercise",
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="plan_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_sessions",
                to="workouts.plansession",
            ),
        ),
    ]
